### PR TITLE
Cloud9 Proposal

### PR DESCRIPTION
**Pull request by diiq**
Not looking for a merge at this time, just surfacing what I've done so other folks can look at it.

Some key things to note:

- I upgraded ruby to 2.5.5. This was not necessary for Cloud9, but was necessary to continue using the ruby-2.5 docker image, and the Cloud9 setup will need to match the docker setup.
- I had to add a database password to the environment. I believe I've done so in a way that will not break local or docker dev; but further testing is *needed* before this merges.
- The block in `config/environments/development.rb` which sets `config.action_controller.asset_host` is something I've never seen before, and it sure doesn't look right to me. It leads to the assets in constant.js to be looked for on localhost:3000, rather than a relative path; maybe the original authors were imagining hosting assets on S3 someday? Unclear. I had to give those assets a relative path in order to get them to bridge the VPC gap on Cloud9. I'm not happy with that choice; but it was the most surgical, and altered the fewest mysteries.

### CODE REVIEW

**Comment by jacebrowning** [comment]
Thanks for working on this!

It looks like some of the images are missing on the review app:

**Comment by diiq** [comment]
> maybe the original authors were imagining hosting assets on S3 someday?

Ah, clearly they were, the assets are fingerprinted in production. I might have to actually address the `asset_host` weirdness.

**Comment by jacebrowning** [comment]
@diiq The Cloud9 URL is http://tiny.cc/lgrow-cloud9 if you'd like to add that somewhere to the docs.

**Comment by beyondtheteal** [comment]
I experienced this problem, so it might be worth documenting in the readme 

https://stackoverflow.com/a/49426727

**Pull request merged**
