### PR TITLE
Set url options to host name

### PR DESCRIPTION
**Pull request by beyondtheteal**
contributes to #112
* Set default_url_options to the asset host.

### CODE REVIEW

**Comment by beyondtheteal** [comment]
In order for this fix to be complete, we must also change `RAILS_ENV` to `staging` on the Heroku app.

**Comment by Ross-Hunter** [comment]
@beyondtheteal what's the reason for changing the `RAILS_ENV`? Rather than relying on the `RAILS_ENV` producing different behavior, I suggest just relying on environment variables. It doesn't look like there are any `if Rails.env.staging?`s in the code (which is good). Staging is not an environment that comes out of the box with Rails and I think using Heroku removes any real need for it.

**Comment by Wilfongjt** [comment]
# What a mess! 
I see the logic of @beyondtheteal, RAILS_ENV is set to "production" in the  staging environment and this screams MISTAKE!
 @Ross-Hunter, I see the order we would gain by picking one method for setting environment variables.   

We need some rules to sort out what we expect RAILS_ENV to do.

I propose:
Setting ENV['RAILS_ENV']='production'  should
* set RAILS_ENV to 'production' only in Heroku's settings
* turn off  dotenv and render the environment vars in  .env useless
* switch the application to the production database
* turn off testing
* RAKE?

Setting ENV['RAILS_ENV']='staging' 
* turn off  dotenv and render the environment vars in  .env useless in the staging environment
* switch the application to the testing/staging  database
* RAKE?

What about RAKE what does RAKE do or not do in staging and production?

**Comment by Ross-Hunter** [comment]
I have found with Rails and Heroku that creating an environment called "staging" only results in pain, and it's much better to build the app conforming to [12 Factor](https://12factor.net/config ). This also complicates review environments and whatnot.`production` really means `deployed` or the non dev/test environment.

**Pull request merged**
