### PR TITLE
remove .env.*

### PR DESCRIPTION
**Pull request by Wilfongjt**

### CODE REVIEW

**Comment by Ross-Hunter** [comment]
Why? I just added these files.

**Comment by Wilfongjt** [comment]
@Ross-Hunter a common developer practice it to ignore .env and not include it in the repo.  This keeps folks from accidentally sharing secrets, passwords, etc from the world.  I see there is a DEVISE_SECRET in .env.development and .env.test.  I'm guessing that devise_secret is the secret key for the SF email service. If you have access to the key you can use SF's email service to send spam or worse. I would suggest we don't publish that key to the internet especially in our repo.

# Try This
I use msecure to encrypt those keys in a file on my local machine.  When i need to use the keys, like after I clone a repo, I create a new .env file and fill it with the required key-value pairs, and drop it into the app folder (i.e., adopt-a-drain/ ).  The application (i.e., AAD) is written to use those .env vars when they are set. We use the dotenv GEM to load up the environment variable automatically from the .env file. This is only done by a developer in their development environment.  

# Anything worth doing is worth over doing
Heroku has its own way of handling environment variables so it doesn't use the .env file. The Heroku admin has to transfer these manually into the Heroku settings found in lgrow-staging and lgrow-production. This minimizes the security exposure.

# Finally 
The github readme.md usually has instructions on how to build a .env for development purposes.  We have instructions in the our repo readme.md that does just that.

**Comment by Ross-Hunter** [comment]
`.env.development` & `.env.test` are perfectly fine for shared non-secret variables. A developer should also create a local `.env` file as well to hold sensitive information, and it should be gitignored. Removing these files breaks the test environment, and creates more work for developers on the project. It is a valid point that these files existing *might* tempt someone to commit a *real* secret, but I believe that to be a small risk, and can be mitigated by adding a comment to the top of these files.

This devise secret is used for creating password reset tokens and the like. I'm not sure where it came from, or why it was committed to the repo, but it was, and unfortunately that can't be undone. If you would like to generate a new one and throw it in there that's fine, but I do not believe we are endangering anyone by leaving this developer-use-only one committed.

A new devise secret has been generated for the deployed environments and that should never be committed to any source control.

**Comment by Wilfongjt** [comment]
# Consider:
Recently, users of AAD have been targeted with phishing attempts. We don't know if AAD is at fault but I take seriously my responsibility to protect the team and the users of AAD.  Education is the most important way to defend against security issues and predictability of process is a very good way to educate a group.

You recently, sent a link to the 12-factor app (https://12factor.net/config) principles.   I quote "...Env vars are easy to change between deploys without changing any code; unlike config files, there is little chance of them being checked into the code repo accidentally;."  I read this as don't store environment variables in your repository. 

I believe that configuring our git repository to ignore environment/config files is important to our overall security. I strongly suggest we adopt this as our rule going forward.

**Pull request closed without merging**
