### PR TITLE
Upgrade to a paid database on review apps

### PR DESCRIPTION
**Pull request by jacebrowning**

### CODE REVIEW

**Comment by jacebrowning** [comment]
Hmm... that change doesn't seem to have taken effect:



https://dashboard.heroku.com/apps/lgrow-staging-pr-93/resources

Any ideas @Ross-Hunter?

**Comment by Ross-Hunter** [comment]
Just co clarify: this was deployed, despite the failed checks?

**Comment by jacebrowning** [comment]
It _appears_ to be deployed.

**Comment by jacebrowning** [comment]
Oh well, I do think this is the correct change.

**Pull request merged**
