### PR TITLE
Refactoring sign up buttons.

### PR DESCRIPTION
**Pull request by oneblackcrayon**
Refactored buttons for login, signup, and password reset.

### CODE REVIEW

**Comment by Ross-Hunter** [comment]
This definitely cleans the code up a lot and is A+ in that regard.

This is what happens when I sign out.
automatically_refresh_my_drains_by_beyondtheteal_ _pull_request__155_ _citizenlabsgr_adopt-a-drain

I think #155 will actually address this issue. I think this PR is approved, but we should merge that first, and also I should get my feature testing PR in first as well to feel more confident in this change.

We also probably want to think through the design and make these buttons a little friendlier. They all look pretty similar and contain the work "form".

**Comment by Ross-Hunter** [comment]
Unfortunately there is a bunch of bad untested javascript tied up in to this form. What you have here is much better than the existing combo-form concept, but it will require teasing apart the existing javascript to get it to work. I was running into problems signing in and started to pull apart the JS and bailed because I don't feel confident rewriting this sidebar right now.

**Comment by oneblackcrayon** [comment]
After signing up for an account and logging out, when attempting to login to the app, you are greeted with:
```The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.

If you are the application owner check the logs for more information.```
URL: [https://lgrow-staging-pr-161.herokuapp.com/sidebar/combo_form](https://lgrow-staging-pr-161.herokuapp.com/sidebar/combo_form
![Screen Shot 2019-03-19 at 8 19 54 PM](https://user-images.githubusercontent.com/233911/54650362-74f71880-4a84-11e9-9d6f-31cbb16876eb.png)
)

**Comment by Wilfongjt** [comment]
# Solved
* split new account, sign in and forgot password into separate forms.

**Pull request merged**
